# Generated by Django 3.1.7 on 2021-06-02 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questions', '0008_auto_20210602_1545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1Solution', models.CharField(max_length=2000)),
                ('player2Solution', models.CharField(max_length=2000)),
                ('player1SolvedTime', models.DateTimeField()),
                ('player2SolvedTime', models.DateTimeField()),
                ('player1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionForComp', to='Questions.questions')),
                ('winner', models.ManyToManyField(related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
