# Generated by Django 3.1.7 on 2021-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='player1Solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playground',
            name='player2Solution',
            field=models.TextField(),
        ),
    ]
