# Generated by Django 3.1.7 on 2021-06-02 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Playground', '0002_auto_20210602_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='winner',
        ),
        migrations.AddField(
            model_name='playground',
            name='winner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
