# Generated by Django 3.1.7 on 2021-06-02 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Playground', '0004_auto_20210602_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playground',
            name='player1Solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playground',
            name='player1SolvedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playground',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playground',
            name='player2Solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playground',
            name='player2SolvedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playground',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
