# Generated by Django 3.1.7 on 2021-06-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0005_auto_20210602_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playground',
            old_name='question',
            new_name='questionForComp',
        ),
    ]
