# Generated by Django 3.1.7 on 2021-05-22 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='userSolution',
            field=models.ManyToManyField(related_name='userSolution', to=settings.AUTH_USER_MODEL),
        ),
    ]
