# Generated by Django 3.1.7 on 2021-05-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0002_solution_usersolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='userSolution',
        ),
        migrations.AddField(
            model_name='solution',
            name='userSolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSolution', to=settings.AUTH_USER_MODEL),
        ),
    ]
