# Generated by Django 3.1 on 2021-05-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_solution_originalsolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='originalSolution',
        ),
        migrations.AddField(
            model_name='questions',
            name='originalSolution',
            field=models.FileField(blank=True, null=True, upload_to='Apps/Questions/Answers/Questions/'),
        ),
    ]
