# Generated by Django 3.1.7 on 2021-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_auto_20210602_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
