# Generated by Django 3.1.7 on 2021-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210529_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPlaying',
            field=models.BooleanField(default=False),
        ),
    ]
